before_script:
  - npm install mocha
  - npm install chai
  - npm install nyc codecov
language: node_js
node_js:
  - "stable"
script:
  - npm test

env:  
  - SECRET=hbjfrjmbnfvmfnvbbfvnmvj

after_success: npm run coverage