before_script:
  - npm install mocha
  - npm install chai
  - npm install nyc codeclimate-test-reporter
language: node_js
node_js:
  - "stable"
script:
  - npm test
env:
  -SECRET=hbjfrjmbnfvmfnvbbfvnmvj
  -export CODECOV_TOKEN="15475461-44a7-4ca7-ad24-24e28b48128f"
