before_script:
  - npm install mocha
  - npm install chai
  - npm install nyc codeclimate-test-reporter
language: node_js
node_js:
  - "stable"
script:
  - npm test
env:
  -SECRET=hbjfrjmbnfvmfnvbbfvnmvj
