before_script:
  - npm install mocha
  - npm install chai
  - npm install nyc codecov coveralls
  - psql -c 'create database travis_ci_test;' -U postgres
language: node_js
node_js:
  - "stable"
cache: npm
script:
  - nyc npm test

services:
  - postgresql

env:
  global:
  - SECRET=hbjfrjmbnfvmfnvbbfvnmvj
  - TEST_DATABASE_URL=postgres://pvnjhgbw:8bR3vBDbAKq09WwhdZyArY2K0Hb7uofp@isilo.db.elephantsql.com:5432/pvnjhgbw
  - NODE_ENV=test

after_success: npm run coverage